- src/prelaunch/axis.assassin.a
- src/prelaunch/captn.goodnight.a
- src/prelaunch/drelbs.a
- src/prelaunch/dung.beetles.a
- src/prelaunch/gorgon.a
- src/prelaunch/head.on.a
- src/prelaunch/impossible.miss.a
- src/prelaunch/juggler.a
- src/prelaunch/kid.niki.a
- src/prelaunch/pac.man.a
- src/prelaunch/quadrant.6112.a
- src/prelaunch/stellar.7.a
Gorgon was turning off accel a little too late. Added accel for pac man and others. Fixed reset (reboot) on some 64k titles.
> Reset vector & accel fixes

- src/prelaunch/jungle.hunt.a
- src/prelaunch/pieman.a
- src/prelaunch/pollywog.a
- src/prelaunch/snack.attack.a
- src/prelaunch/tag.team.a
Jungle hunt seems okay. The others work fine on my fastchip //e.
> Reset Fixes (now with acceleration!)

- src/prelaunch/head.on.a
- src/prelaunch/impossible.miss.a
- src/prelaunch/plasmania.a
- src/prelaunch/shuffleboard.a
- src/prelaunch/space.quarks.a
- src/prelaunch/space.raiders.a
Both Head On and Plasmania clobber $100 on start
> Reset vector fixes

- src/prelaunch/thexder.a
- src/prelaunch/tomahawk.a
- src/prelaunch/wolfen84.a
Tested these on my ][+ tonight so they should be good. Weren't working while LC was switched in.
> Fixes of reset vector fixes

- src/prelaunch/skyfox.a
> Reset vector fix

- src/hw.accel.a
> Fastchip sound setting fix

- src/prelaunch/rescue.raiders.a
don't do last minute changes without testing on real hardware before you ship.
> Fix //c+ Rescue Raiders fix

- src/hw.accel.a
tested on real life //c+ and //e for favorable behavior.
> Fix DHGR/HGR coloring on //c+

- res/GAMEHELP/CANYON.CLIMBER
My first game help file. Tried to match LR formatting. If this is correct, I'll try to make more for games that I know.
> Canyon Climber game help. PR test

- res/GAMEHELP/AZTEC
- res/GAMEHELP/BEER.RUN
- res/GAMEHELP/BRUCE.LEE
- res/GAMEHELP/CANNONBALL.BLTZ
Beer Run
Cannonball Blitz
Bruce Lee    - candidate for further help WRT joystick movements:
up left  is leap left, up right is leap right
up is jump
down is duck
kick is while running, chop is while still
I wasn't sure if necessary.
> Game help from roughana

- res/GAMEHELP/MANIC.MINER
There's no joystick input. C toggles the "camera mode".
> Manic Miner gamehelp update

- src/prelaunch/microwave.a
> Revert "fix Microwave reset"

- src/prelaunch/realm.imposs.a
- src/prelaunch/wayout.a
> reset fixes

- src/prelaunch/pac.man.a
$100 eventually gets overwritten
> fix Pac-Man reset vector

- src/prelaunch/space.eggs.a
> fix Space Eggs reset

- Makefile
- winmake.bat
save 2 blocks by excluding GAMEHELP/STANDARD and PRELAUNCH/STANDARD from the image
add GS icon stuff to winmake
> makefile updates

- Makefile
- winmake.bat
> restore standard prelaunch

- res/GAMEHELP/BATTLE.CHESS
- res/GAMEHELP/HARD.HAT.MACK
Hi,
My first try creating some gamehelp files. Let me know if this is the right process!
Kirk
> Gamehelp kirk

- src/prelaunch/moon.patrol.a
> fix Moon Patrol reset for real this time

- README.md
- res/GAMEHELP/DAVIDS.MAGIC
- res/GAMEHELP/FLIP.OUT
- res/GAMEHELP/LANCASTER
- res/GAMEHELP/SNACK.ATTACK
- res/GAMEHELP/SNAKE.BYTE
- res/GAMEHELP/SNEAKERS
- res/GAMEHELP/STAR.THIEF
- res/GAMEHELP/ZENITH
This includes changes and additions only to text portions of the project. 
The gamehelp files have been tested to make sure the formatting is not overflowing or breaking anything. Most of these came from Alex Lee via Slack.
> Text cleanups

- src/hw.accel.a
- src/hw.joystick.a
should fix https://github.com/a2-4am/4cade/issues/335
> fix Fastchip joystick detection on older firmware

- res/history.md
The original source for 10 of Alex's crops came from contributions by mr_breaddoughrising (preferred handle)
> Add credit for contributed artwork

- src/prelaunch/spy.hunter.a
vectors are wonky while it plays the song
> tweak Spy Hunter reset

- src/prelaunch/wargle.a
> fix Wargle reset

- src/prelaunch/space.race.a
> fix Space Race reset

- src/prelaunch/flak.mb.a
return to TR instead of going back to title screen
> fix Flak reset after title screen

- res/GAMEHELP/EVOLUTION
- res/GAMEHELP/KUNG.FU.MASTER
Created by referring to https://archive.org/stream/Apple2Manuals/Kung%20Fu%20Master%20%28USA%29l
Please add label to the PR to accept it for Hacktoberfest as per
https://hacktoberfest.com/participation/#maintainers
> Kung Fu Master game help

- README.md
Can't build from a ZIP file, as it can't pull the commit number.
> clarify Linux instructions

- src/fx/fx.hgr.radial.common.a
- src/prelaunch/apple.invader.a
Uses LDA/BIT $C033 instead of $C030 for some reason.
> fix Apple Invader sound on //gs

- src/demo/dino.eggs.a
> fix hang in Dino Eggs demo on //gs

- src/macros.a
fixes attract hanging on ROM0 and ROM1 machines
> Fix Alternate Display Mode on ROM0 and ROM1 //gs

- src/4cade.init.a
- src/demo/gamma.goblins.a
- src/macros.a
- src/prelaunch/gamma.goblins.a
We now control the horizontal. We now control the vertical. We now control the '2' shadow bank of //gs video memory. Improves The Goonies and Pacman demos on ROM0/1.
> Clear //gs Shadow Page 2

- res/GAMEHELP/MAPPLE
I haven't managed to get past level 1.
> Add MAPPLE gamehelp

- res/GAMEHELP/MINIT.MAN
Referred to scanned manual on Asimov
> Add MINIT.MAN game help

- res/GAMEHELP/ANGEL.1
- res/GAMEHELP/AO
- res/GAMEHELP/B1
- res/GAMEHELP/B2
- res/GAMEHELP/BEZARE
- res/GAMEHELP/BEZOFF
- res/GAMEHELP/BH
- res/GAMEHELP/BLOODSUCKERS
- res/GAMEHELP/BORG
- res/GAMEHELP/BT
- res/GAMEHELP/BY
- res/GAMEHELP/CAPTAIN.POWER
- res/GAMEHELP/CAVRN.CREATURES
- res/GAMEHELP/HORIZON.V
Additional game help for #637 
- Angel-1
- Apple Oids
- Beachhead
- Beachhead 2
- Bezare
- Bezoff
- Bongo's Bash
- Bloodsuckers
- Borg
- Bill Budge Trilogy
- Bats in the Belfry
- Captain Power 
- Cavern Creatures
- Horizon V
> Additional help text

- res/GAMEHELP/CHIP.OUT
- res/GAMEHELP/COLLECT
- res/GAMEHELP/CREEPY.CRRIDORS
- res/GAMEHELP/CRICKATEER
- res/GAMEHELP/CUBIT
- res/GAMEHELP/DEMONIC.DECKS
- res/GAMEHELP/DEPTH.CHARGE
> Additional game help

- res/GAMEHELP/ALIEN.AMBUSH
- res/GAMEHELP/ALIEN.DOWNPOUR
- res/GAMEHELP/ALIEN.TYPHOON
- res/GAMEHELP/ORBITRON
Ref https://github.com/a2-4am/4cade/issues/637
Add Orbitron help text (Thanks to Alex Lee)
Update some others for consistent terminology
> Add Orbitron

- res/GAMEHELP/DAWN.TREADER
- res/GAMEHELP/DEEP.SPACE
- res/GAMEHELP/DOUBLE.TROUBLE
- res/GAMEHELP/ES
- res/GAMEHELP/FAT.CITY
- res/GAMEHELP/FIRE.AND.ICE
- res/GAMEHELP/FIREBIRD
- res/GAMEHELP/FLOBYNOID
- res/GAMEHELP/FLOPPY
- res/GAMEHELP/FRAZZLE
Game keys were derived by looking for the LDA $C000 present in memory using the Inspector and Watson in a switchable ROM configuration.
> Added game documentation for 10 games.

- res/GAMEHELP/GB.TETRIS
Updated game help for Game Boy Tetris to include missing keys. I did my best to adhere to the existing format. LMK if you have any questions.
Thanks!
Lee
> update gb tetris game help

- src/prelaunch/millnm.leaper.a
- src/prelaunch/the.last.ninja.a
LC1 is banked in at the point we turn off SHR artwork.
> fix The Last Ninja startup

- RANDAMN
https://github.com/a2-4am/4cade/issues/637
> Create RANDAMN help text
